version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: giftuser
      POSTGRES_PASSWORD: giftpass
      POSTGRES_DB: gifty_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U giftuser -d gifty_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: